language: python

services:
  - postgresql
  - mysql

python:
  - "2.7"

branches:
  only:
    - master

before_install:
  - pip install -U pip

# command to install requirements
install:
  - pip install -U pip wheel setuptools
  - pip install -r requirements.txt
  - python setup.py develop -q
  - pip install coverage coveralls selenium lxml
  - pip install MySQL-python

before_script:
  # - export DISPLAY=:99.0
  # - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - psql template1 -c 'CREATE EXTENSION hstore;'
  - psql -U postgres -c 'CREATE DATABASE nodeshot_ci;'
  - psql -U postgres -d nodeshot_ci -c "CREATE EXTENSION postgis;"
  - psql -U postgres -d nodeshot_ci -c "CREATE EXTENSION postgis_topology;"
  - mysql -e 'create database nodeshot_old_ci;'
  - cd tests
  - ./manage.py syncdb --noinput --no-initial-data
  - ./manage.py migrate --noinput --no-initial-data
  - ./manage.py loaddata initial_data

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source=nodeshot runtests.py

after_success:
  coveralls
archive: true
