language: python

services:
  - postgresql
  - mysql

python:
  - "2.7"

branches:
  only:
    - master

# command to install requirements
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coverage coveralls --use-mirrors
  - python setup.py install
  - pip install MySQL-python

before_script:
  - psql template1 -c 'CREATE EXTENSION hstore;'
  - psql -U postgres -c 'CREATE DATABASE nodeshot_ci;'
  - psql -U postgres -d nodeshot_ci -c "CREATE EXTENSION postgis;"
  - psql -U postgres -d nodeshot_ci -c "CREATE EXTENSION postgis_topology;"
  - mysql -e 'create database nodeshot_old_ci;'
  - cd tests
  - python manage.py syncdb --noinput
  - python manage.py migrate --noinput
  - python manage.py collectstatic --noinput
  - python manage.py runserver 0.0.0.0:8000 &

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source=nodeshot runtests.py

after_success:
  coveralls
